pipeline {
    agent any

    stages {
        stage('Create build folder') {
            steps {
                script {
                    env.BUILD_DIR = "C:/Jenkins Deployment/Frontend/Demo/${new Date().format('MM-dd-yyyy_HH-mm-ss')}"
                    echo "Creating build folder: ${env.BUILD_DIR}"
                    bat "mkdir \"${env.BUILD_DIR}\""
                }
            }
        }

        stage('Checkout application code') {
            steps {
                dir("${env.BUILD_DIR}") {
                    checkout([
                        $class: 'GitSCM',
                        branches: [[name: '*/main']],
                        userRemoteConfigs: [[
                            url: 'https://github.com/aanujbhhardwaj1/Commissions-Web.git',
                            credentialsId: 'github-pat-credentials-id'
                        ]]
                    ])
                }
            }
        }

        stage('Deploy static frontend') {
            steps {
                echo "Static frontend deployed successfully"
            }
        }
    }
}


